### PR TITLE
Making GraphDef Editor compatible with TensorFlow 2.x

### PR DESCRIPTION
**Pull request by vlasenkoalexey**

### CODE REVIEW

**Comment by vlasenkoalexey** [comment]
It should work with TF2.x now #33

**Comment by vlasenkoalexey** [comment]
Hi @frreiss and @BryanCutler,

Do you guys plan to maintain this project?
I'd like to use it in one of the products I'm working on, and have few things I'd like to contribute.
Would you mind adding me as a project contributor?

Thanks,
Aleksey

**Comment by BryanCutler** [comment]
Hi @vlasenkoalexey , thanks for the PR! Because of other projects taking precedence, this has fallen by the wayside for the time being. That is great if you would like to use it and contribute, I'll be happy to review and merge PRs. I might be a little slow with the holidays coming up though :)

**Review by BryanCutler — APPROVED** [review]
LGTM

**Pull request merged**
